name: "CSV Test"
description: "Test using github actions to populate a CSV"
author: "Jose Maia"
inputs:
  myInput:
    description: "Input to use"
    default: "world"
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
