name: Update CSV
on:
  push:
    branches:
      - master
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - uses: actions/checkout@v1

      - name: create csv file
        run: echo '${{ steps.create_csv.outputs.csv }}' > ./sampleFiles/a.csv

      - name: git add
        run: git add -N ./sampleFiles/a.csv

      - uses: stefanzweifel/git-auto-commit-action@v2.1.0
        with:
          commit_message: Update csv
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
