name: Update CSV
on:
  push:
    branches:
      - master
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - uses: actions/checkout@v1

      - uses: josemaia/csv-python-action@master
        with:
          myInput: teste
        id: create_csv

      - name: create csv file
        run: echo '${{ steps.create_csv.outputs.myOutput }}' > ./sampleFiles/a.csv

      - name: git add
        run: git add -N ./sampleFiles/a.csv

      - uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: Update CSV
